# pracctice opearators and aggregations

CREATE DATABASE ordersDB;
USE ordersDB;

CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    name VARCHAR(50),
    department VARCHAR(50),
    salary INT,
    hire_date DATE
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    employee_id INT,
    product VARCHAR(50),
    amount INT,
    order_date DATE,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);

INSERT INTO employees (employee_id, name, department, salary, hire_date) VALUES
(1, 'Alice', 'Sales', 60000, '2021-03-15'),
(2, 'Bob', 'Sales', 75000, '2020-07-10'),
(3, 'Charlie', 'IT', 90000, '2019-11-20'),
(4, 'Diana', 'IT', 120000, '2018-05-01'),
(5, 'Ethan', 'HR', 50000, '2022-01-12'),
(6, 'Fiona', 'HR', 55000, '2021-09-30'),
(7, 'George', 'IT', 95000, '2020-02-25');

INSERT INTO orders (order_id, employee_id, product, amount, order_date) VALUES
(101, 1, 'Laptop', 1200, '2023-01-10'),
(102, 1, 'Mouse', 25, '2023-01-11'),
(103, 2, 'Keyboard', 70, '2023-01-12'),
(104, 3, 'Monitor', 300, '2023-02-01'),
(105, 3, 'Laptop', 1500, '2023-02-05'),
(106, 4, 'Server', 5000, '2023-03-10'),
(107, 5, 'Desk', 200, '2023-03-15'),
(108, 6, 'Chair', 150, '2023-03-20'),
(109, 7, 'Laptop', 1300, '2023-04-01'),
(110, 7, 'Mouse', 30, '2023-04-02');

SELECT * FROM employees;
SELECT * FROM orders;

# Find all employees with a salary greater than 80,000.
SELECT name, salary 
FROM employees
WHERE salary >= 80000;

#List employees who joined before 2020-01-01.
SELECT name, hire_date
FROM employees 
WHERE hire_date < '2020-01-01';

# Get all orders where the amount is greater than 1000.
SELECT order_id, product, amount
FROM orders
WHERE amount > 1000;

# Show employees who belong to the IT department.
SELECT employee_id, name, department
FROM employees
WHERE department = 'IT';

# Retrieve orders placed after 2023-02-01.
SELECT order_id, product
FROM orders
WHERE order_date > '2023-02-01';

# Find the total number of employees in each department.
SELECT department, COUNT(*) AS total_employees
FROM employees
GROUP BY department;

# Calculate the average salary per department.
SELECT department, AVG(salary)
FROM employees
GROUP BY department;

# Find the total order amount for each employee.
SELECT employee_id, SUM(amount) AS total_spent
FROM orders
GROUP BY employee_id;

# Find the number of orders placed for each product.
SELECT product, COUNT(*) AS quantity
FROM orders
GROUP BY product;

# Find the total revenue generated by all orders combined.
SELECT SUM(amount) AS revenue
FROM orders;

SELECT * FROM employees, orders;

# Show all employees along with their orders (include employees with no orders).
SELECT e.name, o.product
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id;

# Find employees who have placed at least one order.
SELECT DISTINCT e.*
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id;

# Show employee name and total order amount per employee.
SELECT e.name, SUM(o.amount) AS total_amount
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.name;

# Find departments along with total order revenue generated by each department.
SELECT e.department, SUM(o.amount) AS revenue
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.department;

# List all orders with employee name and department.
SELECT e.name, e.department, o.*
FROM employees e
RIGHT JOIN orders o ON e.employee_id = o.employee_id;

SELECT e.name, e.department, o.product, o.amount
FROM employees e
RIGHT JOIN orders o ON e.employee_id = o.employee_id;

SELECT * FROM employees, orders;
# Find employees who have never placed an order.
SELECT e.*
FROM employees e
LEFT JOIN orders o ON e.employee_id = o.employee_id
WHERE o.order_id is NULL;

# Find the employee who generated the highest total order amount.
SELECT e.name, SUM(o.amount) AS total_amount
FROM employees e 
LEFT JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.name
ORDER BY total_amount DESC
LIMIT 1;

# Find the product that generated the highest revenue.
SELECT product, SUM(amount) AS revenue
FROM orders 
GROUP BY product
ORDER BY revenue DESC
LIMIT 1;

# Find departments where the average salary is greater than 80,000.
SELECT department, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING avg_salary > 80000;


# Find employees who have placed more than 2 orders.
SELECT e.name, COUNT(o.product) AS no_orders
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.name
HAVING no_orders >= 2;

